[build]
  publish = "."
  command = "echo 'Static site build complete'"

[[redirects]]
  from = "/"
  to = "/static-index.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/chat.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000"
